### ISSUE TITLE
export出来的PDF文件中，有几个地方显示有bug

### ISSUE THREAD

**Issue by bobdos** [leaf-hsiao/catfish#2]
在export出来的PDF文件中，
1. 代码块部分：语法高亮没有了。代码都是黑色字体了，和背景混在一起，看不清楚。
2. Table of Contents: 没有蓝色高亮显示。

**Comment by leaf-hsiao** [comment]
可以给出详细说明吗，无法复现 bug
![test](https://user-images.githubusercontent.com/9102854/30948872-8578672c-a445-11e7-96a7-e1aadd76300a.png)

**Comment by bobdos** [comment]
今天重新测试了一下，换Google Chrome 61 - Windows 10 打开PDF，一切正常。

所以估计是之前用的pdf阅读器的问题：Adobe Reader XI - Windows 10
