### ISSUE TITLE
CodeMirror光标难以看清

### ISSUE THREAD

**Issue by sxq112358** [leaf-hsiao/catfish#3]
因为背景是深色的，而光标表现为1px solid black
搜了一下找到了这个[https://github.com/graphql/graphiql/pull/547/files](https://github.com/graphql/graphiql/pull/547/files)
跟他相反，在css里关于cursor的两行前面添加上`div`
`.cm-s-inner div.CodeMirror-cursor { border-left: 1px solid #f8f8f0; }`
`.cm-s-typora-default div.CodeMirror-cursor { border-left: 1px solid #f8f8f0; }`

然后颜色就正常了。。不会css，不知道是哪里的问题

**Comment by leaf-hsiao** [comment]
已解决
