### ISSUE TITLE
 代码部分的注释颜色太过亮蓝

### ISSUE THREAD

**Issue by ningblue** [leaf-hsiao/catfish#4]
![image](https://user-images.githubusercontent.com/22655294/32367973-1be13a64-c0bf-11e7-9eda-a6bf4a4b9520.png)

能不能调整一下下？谢谢

**Comment by leaf-hsiao** [comment]
配色直接使用的 [CodeMirror](https://codemirror.net/) 的 material 配色，需要修改的可以选择合适的[主题](https://codemirror.net/demo/theme.html)直接替换。
