### ISSUE TITLE
Unreadable diagram preview font color

### ISSUE THREAD

**Issue by ghost** [leaf-hsiao/catfish#6]
When using mermaid diagrams or flow chars, the font color makes it impossible to read. I tested it on windows and osx with the same results. I added the following lines to catfish.css and it's a lot better this way.

```
.md-diagram-panel-preview {
  color: #263238;
}
```

This theme is now my favorite, thank you for your work!

**Comment by leaf-hsiao** [comment]
Thanks for your help, you can create a pull request to this repository. Anyway, I will fix it.
