### ISSUE TITLE
代码部分颜色高亮奇怪

### ISSUE THREAD

**Issue by lartpang** [leaf-hsiao/catfish#9]
![image](https://user-images.githubusercontent.com/26847524/45361716-8529c900-b605-11e8-9841-503ab59aee16.png)

图中的红色部分，这是为何？
Ubuntu 18.04LTS

**Comment by leaf-hsiao** [comment]
能否提供具体的文件

**Comment by lartpang** [comment]
就是这个文件的这个部分

https://github.com/lartpang/ML_markdown/blob/master/%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C.md#%E6%99%AE%E9%80%9A%E9%9A%8F%E6%9C%BA%E5%A4%B1%E6%B4%BB

感谢

**Comment by leaf-hsiao** [comment]
尝试一下把2个空格的缩进改成4个空格的缩进

**Comment by lartpang** [comment]
确实有所改善，非常感谢提供这么优秀的主题。

不过请问这个问题的原因是什么呢？没有办法从主题上修改么？

**Comment by leaf-hsiao** [comment]
CodeMirror 插件的问题，实现原理请参考 https://codemirror.net/doc/manual.html#api 主题上无法修改
